# Generated by Django 4.2.13 on 2025-01-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_shippingsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprovider',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
