# Generated by Django 4.2.13 on 2024-05-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_customer_id_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('received', 'Received'), ('boxing', 'Boxing'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='shipping', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbasket',
            name='status',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('received', 'Received'), ('boxing', 'Boxing'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='shipping', max_length=20),
        ),
    ]
