# Generated by Django 4.2.13 on 2024-05-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status_orderbasket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_delivery_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderbasket',
            name='items_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderbasket',
            name='items_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderbasket',
            name='shipping_charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
