# Generated by Django 4.2.13 on 2024-05-19 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_shippingsource'),
        ('orders', '0004_alter_order_customer_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasket',
            name='shipping_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.shippingsource'),
        ),
    ]
