# Generated by Django 4.2.13 on 2024-05-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderbasket_shipping_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('boxing', 'Boxing'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderbasket',
            name='status',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('received', 'Received'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='shipping', max_length=20),
        ),
    ]
