# Generated by Django 4.2.13 on 2024-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_alter_orderbasket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
