# Generated by Django 4.2.13 on 2024-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasket',
            name='total_paid_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
