# Generated by Django 4.2.13 on 2024-05-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderbasket_total_paid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='orderbasket',
            name='notes',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
