# Generated by Django 4.2.13 on 2024-05-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_shippingsource'),
        ('orders', '0009_order_notes_orderbasket_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.deliveryprovider'),
        ),
    ]
