# Generated by Django 4.2.13 on 2025-02-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_delivery_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasket',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
